### PR TITLE
Dynamic execution path and load from file function

### PR DESCRIPTION
**Pull request by ketangupta34**
# Description
 - java loader execution_path - Add execution path function and bootstrap_execution_path functions
 - java_load_from_file - compiling class and storing in an handle 

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #(issue_no)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation update

# Checklist:

- [ ] My code follows the style guidelines (clang-format) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests/screenshots (if any) that prove my fix is effective or that my feature works.
- [ ] I have tested the tests implicated (if any) by my own code and they pass (`make test` or `ctest -VV -R <test-name>`).
- [ ] If my change is significant or breaking, I have passed all tests with `./docker-compose.sh &> output` and attached the output.
- [ ] I have tested my code with `OPTION_BUILD_SANITIZER` and `OPTION_TEST_MEMORYCHECK`. 
- [ ] I have tested with `Helgrind` in case my code works with threading.
- [ ] I have tested with `Helgrind` in case my code works with threading.
- [ ] I have run `make clang-format` in order to format my code.

If you are unclear about any of the above checks, have a look at our documentation [here](https://github.com/metacall/core/blob/develop/docs/README.md#63-debugging)

### CODE REVIEW

**Comment by viferga** [comment]
As we talked in Discord chat, the execution path is wrong. You are using it for storing the compilation output of the load_from_file but that's not the same as appending paths into the `classpath` which is the idea of the execution path.

The compilation path can be the same as the one that is provided by the file from load_from_file or `LOADER_SCRIPTS_PATH`.

I think we should divide this into two things, one is the path you use to build (which you need it to be in the classpath too in order to load later on the classes), and the other is the classpath itself.

This means, for example, if I have a random folder, different from `LOADER_SCRIPTS_PATH` or `LOADER_LIBRARY_PATH`, I should be able to do this:
```c
metacall_execution_path("java", "/random/folder");
metacall_load_from_package("java", "SomePrebuiltClassFromRandomFolder");
```

Something like this should be doable, not sure if we should pass a extension to the package method (like `SomePrebuiltClassFromRandomFolder.class` or `SomePrebuiltClassFromRandomFolder.jar`) but that is the general idea.

Here's an example of what I am talking about: https://stackoverflow.com/a/402570

By the way, do not focus on this too much, we can still use hardcored paths for development and review this later on once discover and calls are implemented as we talked.

**Comment by viferga** [comment]
The rest is correct, you got the idea of the Handle refactor. I am going to merge it.

**Comment by ketangupta34** [comment]
Okay, i got what you said, i am gonna work on the execution path as discussed and make the required changes!!

**Comment by viferga** [comment]
@ketangupta34 I've got an idea while writing this, so you don't have to change a lot the path thing, let me write it down:

**Comment by viferga** [comment]
Probably we can just change this:
```java
private static String executionPath;
```
By:
```java
private static String[] executionPaths;
```
Or more safely:
```java
private static Set<Path> executionPaths;
```
And once we load something, you pass the array to the URLClassLoader. What do you think about?

**Comment by ketangupta34** [comment]
Yes, this approach will work better and can make the working more dynamic!!. Instead of just a single classpath we can iterate over the set and find for the pkg.

**Pull request merged**
